### ISSUE TITLE
Sort by payment type

### ISSUE THREAD

**Issue by Miserlou** [opensourcedesign/jobs#128]
Currently have to scroll through all to see which are paid opportunities

**Comment by evalica** [comment]
Yes, that would be nice. Another filter I would love would be the job type, since for example I would be interested just in interaction design positions.

**Comment by evalica** [comment]
Some more ideas about filtering (although this issue was perfect since it was specific, I still want to make this comments in order for the implementation to be extendible):
- There is no way to see the resolved jobs (in order to determine the board's success)
- The filtering is by date of posting, but this is not obvious. Apparently there is no order in the listing. Having that said it's hard to know which entries are still relevant/recent. We should have a rule to deprecate/close older than x entries.

**Comment by bnvk** [comment]
Closing as migrated to opensourcedesign/opensourcedesign.github.io#83
