### ISSUE TITLE
Graphic design for FOSSASIA conference (t-shirt + some artwork)

### ISSUE THREAD

**Issue by victoria-bondarchuk** [opensourcedesign/jobs#149]
[FOSSASIA 2017](http://2017.fossasia.org/) - one of the biggest open source conference in Asia, is looking for help to design few things:
 - T-shirt *(main)* 
 - Name badge
 - X-stand banner
 - Poster 

This year theme is `Artificial Intelligence and Personal Assistants`. 

FOSSASIA 2017 design will have a great exposure: it will be showcased on T-shirts and website, will also be used to create an atmosphere for the party night at the conference. 

**Deadline:** February 15, 2017 
**Reference:**  FOSSASIA logo and some of the sample work from previous years here: https://github.com/fossasia/fossasia-artwork  
**Compensation:**  FOSSASIA is run by volunteers, we can offer free t-shirts and public recognition!

**Comment by simonv3** [comment]
Here's the job listing: http://opensourcedesign.net/jobs/jobs/2017-01-30-Graphic%20design%20for%20FOSSASIA%20conference%20(t-shirt%20+%20some%20artwork)

**Comment by elioqoshi** [comment]
I'd be happy to work on it, but the timeline is pretty rough :/
This is for the general FOSSASIA event, right?

**Comment by ajmos** [comment]
How open are you to having the attendees write stuff on their tshirt in permanent marker?

**Comment by linchocolatte** [comment]
I'll give it a go! (:

**Comment by Ashlxylry** [comment]
![img_0871](https://cloud.githubusercontent.com/assets/20594294/22932594/66ab88f4-f303-11e6-9a49-6458316ee319.JPG)

**Comment by purynova** [comment]
Hello, I gave it a try, here are my designs. 
I used red as a main color since red is official color of the conference and website's design. 
I came up with an idea of a hexagon face to play around of the conference theme, 
which is artificial intelligent. Faces of AI. Please, let me know what you thinks. 
Bellow you can seen t-shirt and banner designs. Poster background sample, and some other mock ups.
![foss_final_vic-01](https://cloud.githubusercontent.com/assets/16286356/23633965/3726ca04-030b-11e7-8462-1975774987ba.png)
![foss_final_vic-02](https://cloud.githubusercontent.com/assets/16286356/23633966/376572fe-030b-11e7-8cca-71a32844a7c7.png)
![fossasia-iot-2017-banner-master-path-01](https://cloud.githubusercontent.com/assets/16286356/23633977/42675262-030b-11e7-90fc-0152319f8a89.jpg)
![foss_poster_bg-01](https://cloud.githubusercontent.com/assets/16286356/23633988/4da60bd2-030b-11e7-9f52-b9a00f2179bf.jpg)
![foss1](https://cloud.githubusercontent.com/assets/16286356/23633999/60fc13fc-030b-11e7-909b-8d3727d2fd99.jpg)
![foss2](https://cloud.githubusercontent.com/assets/16286356/23634001/62cffa5e-030b-11e7-9760-b2e4b5274fce.jpg)
![foss3](https://cloud.githubusercontent.com/assets/16286356/23634004/6391e1e6-030b-11e7-9519-420ceda5d716.jpg)

**Comment by evalica** [comment]
Very nice @purynova

**Comment by victoria-bondarchuk** [comment]
@purynova great work! thank you very much! I will share it with the team and will keep you updated.

**Comment by victoria-bondarchuk** [comment]
Just wanted to say thank you to @purynova and congratulate her on the fist contribution to open source!! 
FOSSASIA 2017 is going great, everyone loves t-shirts, tote bags!

![screen shot 2017-03-19 at 14 02 19](https://cloud.githubusercontent.com/assets/4408326/24078608/ecc19e70-0cac-11e7-9a62-bc3ae2efebcf.png)
![screen shot 2017-03-19 at 14 02 34](https://cloud.githubusercontent.com/assets/4408326/24078609/ecc19cc2-0cac-11e7-962b-75dd90c5248d.png)
![screen shot 2017-03-19 at 14 02 51](https://cloud.githubusercontent.com/assets/4408326/24078610/ecc1b7ac-0cac-11e7-9ec4-942de7f3a8d7.png)
![screen shot 2017-03-19 at 14 07 07](https://cloud.githubusercontent.com/assets/4408326/24078627/61371136-0cad-11e7-9a97-62ce83b85ab8.png)
photos credit: https://www.flickr.com/photos/comprock/albums/72157678094595694/page1

**Comment by belenbarrospena** [comment]
It looks amazing. Great work @purynova <https://github.com/purynova>

**Comment by victoria-bondarchuk** [comment]
I guess this issue should be closed ;)) I hope there will be one more next year~ 
Thank you

**Comment by Erioldoesdesign** [comment]
Gonna assume I can close the open source design jobs board issue associated with this? https://opensourcedesign.net/jobs/jobs/2017-01-30-Graphic%20design%20for%20FOSSASIA%20conference%20(t-shirt%20+%20some%20artwork)
