### ISSUE TITLE
Graphic design talent *using* FOSS

### ISSUE THREAD

**Issue by ryangorley** [opensourcedesign/jobs#173]
I'm interested in subcontracting graphic design work (branding, print, signage, etc.) from [my agency](https://dijt.co) out to designers who use free software (GIMP, Scribus, Inkscape, etc.) to create with. This would be for a variety of ongoing work, and not something I would want to post a listing for on a project-by-project basis. Because the job board is really geared to jobs to support free software projects, rather than traditional jobs _using_ free software, I'm not sure where/how to best get started. I need to find people who have the experience, skill sets, and design sensibilities I need, and are interested in freelancing. Any suggestions?

**Comment by elioqoshi** [comment]
Hi @ryangorley !

I've founded Ura Design ( https://ura.design ) where we work with Open Source projects AND use Free Open Source software ourselves. I have founded it 8 months ago and we have done work for larger Open Source Projects, including Mozilla and the Tor Project. Feel free to ping me if you want to chat :)

**Comment by ryangorley** [comment]
@elioqoshi Awesome. I'll be reaching out to you for more information.

**Comment by jancborchardt** [comment]
@ryangorley awesome initiative! :) So just to confirm, this is explicitly about getting designers who use open source design _tools_ to make design, but for _proprietary_ projects, right? Because if the result would be open source, you can of course post a job like this here. :)

And in general it brings up the important flipside for the jobs page – one that @clintonhalpin was touching with designopensrc.com (https://github.com/clintonhalpin/designopensrc) – also having a listing of the interested designers to browse. There people could for example list the projects they worked on, the tools they use, and more.

What do you think @ryangorley @belenbarrospena @bnvk @elioqoshi @simonv3 @evalica @victoria-bondarchuk?

**Comment by belenbarrospena** [comment]
I think having a section for designers, with some kind of CV and portfolio, would make a lot of sense. It would open the possibility of companies contacting designers directly, which some might want to do, and become a new venue for designers to find work. Would it be somehow connected to the existing [member's list](https://github.com/orgs/opensourcedesign/people)? Or not really?

This conversation and [this issue](https://github.com/opensourcedesign/organization/issues/56) are somehow showing that we might be entering a "phase 2" of the job board. 

When we started it, there was some urgency to the whole thing and we felt we had to get "something" out. We focused on that, which was the right thing to do and has worked out great, but it also meant we didn't necessarily discuss long term plans or vision. Maybe it's time to start that conversation now. Would this be something for our next call?

**Comment by evalica** [comment]
Not sure how I feel about this. Still some note: IMO the main focus of this group was open source projects. For example, some designers could have used proprietary tools to create deliverables for open source projects, but if the deliverables are exported in open formats and provided, it was still ok. 

We have all kinds of concepts here, from open design, to open source tools, to open source deliverables, to open source projects as target, or some parts replaced by proprietary. 
I agree that purist approaches can be limiting, but I think we need to clearly define what we are doing and promoting. A similar question about the job board was in https://github.com/opensourcedesign/jobs/pull/175 . We don't allow / promote any type of job in our organization. 

There are so many platforms where jobs can be found and we stand out for a particular reason. I am not sure how I feel about agencies who are using free software in order to cut costs and try to package it as FOSS related.

Regarding Belen's note about CV and portfolio: again not sure. In theory sounds good. 
In practice we did work for organizations and we didn't report back the fail or success of our results. The process was externalized and lost any connection with the organization. The lines are blurry and we don't enforce anything, since that would drive some people away (and we are still growing). Yet, this blurriness might be also a reason for people to not feel confident in our motives / vision / reasons.

**Comment by ryangorley** [comment]
@jancborchardt You're correct. My intent is to hire people that use open source software, because I would like to promote its adoption in professional circles by demonstrating its effectiveness. The perception among my peers is that Blender, GIMP, Inkscape, etc. are purely for hobbyists. The tools themselves would get better if there were more professionals and creative organizations using them and donating/contributing to them.

I cannot speak for others, @evalica, but in my case this is certainly not really a cost-saving measure. I spend far less time completing projects in proprietary tools because they're less familiar to me and in many instances less mature. Additionally I have to retrain staff to use GIMP instead of Photoshop, Inkscape instead of Illustrator, etc. because these are not currently regarded as industry tools and as such are not taught in schools (at least here). It is a recursive problem that I would like to solve by doing things the more costly way for the greater good. That being said, it is still a work-in-progress, and I continue to have this debate internally when something is just easier to do in a proprietary tool. I'm hoping some day that the open tools will be better, not just gratis.

I didn't gather that this was within the traditional scope of the collective, I mostly asked because I figured people here would be more likely to use these tools. I agree that the publishing CVs could get out of hand. I do think _supporting_ creative tools that abide by open ideals by _using_ these tools certainly should be part of the conversation somehow--if not here, somewhere.

**Comment by jancborchardt** [comment]
So this seems resolved – @ryangorley awesome on pushing open tools! :) Hope to see you and the designers you work with who use open tools on our forum at https://discourse.opensourcedesign.net

I’ll just close this issue cause we want to have all issues related to the website (including job board) in our website issue tracker at https://github.com/opensourcedesign/opensourcedesign.github.io/issues (less confusion where issues are ;) – if it’s still relevant please reopen there. :)
