### ISSUE TITLE
Categories for job board

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/jobs#198]
At the Berlin meetup we talked about adding categories to the job board. That is, a way for the projects to define what exactly they need help with.

This would be useful because:

- Projects can easily choose what they need
- We can showcase which kinds of jobs you can post
- They provide a way to filter
- We know where help is needed most

Best would be 5 concise categories:

1. Logo design & branding
2. Web design
3. Interaction design
4. Usability review & research
5. Other like slides, icons, etc.

We would put these very prominently on the top with icons to filter. And same in the submission form for defining the category.

cc @janushead @jdittrich @guiguru @HeikoTietze @simonv3 @bnvk @belenbarrospena

**Comment by belenbarrospena** [comment]
I agree on adding categories, but I am a bit confused by the "Website
design" one. It seems to mix up design activities with the technical
platforms they are applied to. To create a website, you need interaction
design, user research, graphic design and content design.

I would go for:

* Design research (usability review, usability testing, formative
activities, etc)
* Interaction design (information architecture, software structure and
behaviour)
* Graphic design (logos, icons, branding and visual identity)
* Content design (content production and metadata)

Or something along those lines. You know what I mean :)

It should be possible to select more than one category, I think.

I would also add a short description for each category somewhere, to help
job posters identify what they want.

Just my 2c

**Comment by guiguru** [comment]
I can see how @belenbarrospena’s 4 categories (Design research, Interaction design, Graphic design, Content design) are more ‘correct’ from our pov—at least they are a lot more orthogonal.

but there is more going on than just being correct.

the categories need to be tuned to the realities of design in the software industry, and the terms offered need to quickly help people who are (completely) not in design to express what they are asking for.

thus having two (really large) buckets labeled ‘Logo design & branding’ and ‘Web design’ is just practical. I expect them to be generously filled, all the time.

@jancborchardt & @jdittrich’s number 5 (Other like slides, icons, etc.) is another graphic & content bucket; an overflow bucket. I am curious what will turn up there.

because at the end of the day these categories are also a research tool for us, to get our preconceptions confirmed or rejected.

**Comment by belenbarrospena** [comment]
@guiguru is right if our aim is to create a research tool and 
> to get our preconceptions confirmed or rejected.

I was hoping our aim would more about exposing the breath of design activities to those who might not be familiar with them.

**Comment by bnvk** [comment]
There is already [an issue for this](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/70) with much discussion.

Please, only post "web dev" tasks about the job board on [website repo](https://github.com/opensourcedesign/opensourcedesign.github.io/issues)

**Comment by guiguru** [comment]
hmmm, this closing seems to be, ehm, not very well timed.

**Comment by jancborchardt** [comment]
Moved the points I made in the original posting to the issue at https://github.com/opensourcedesign/opensourcedesign.github.io/issues/70#issuecomment-296164054 which @bnvk linked. :)
