### ISSUE TITLE
Come on in, say hi.

### ISSUE THREAD

**Issue by yoroy** [opensourcedesign/jobs#3]
Small experiment to see if more design folk can make it to this thread. Some of us are hanging out in #opensourcedesign on IRC already, but IRC is not the easiest of channels to get on to.

If you’re interested in whatever intersection of design and open source, introduce yourself in here so that we may get to know eachother a bit better and have a bit more permanent place to check in than on IRC.

Welcome!

**Comment by yoroy** [comment]
My name is Roy, I'm an interaction designer based in the Netherlands. [I contribute to Drupal](https://www.drupal.org/u/yoroy). I attended and spoke at the open source design devroom at Fosdem2015.

I'm good at turning ideas into a plan for something that can be built, turning word documents into wireframes. I make abstract art in the form of etchings and monoprints.

**Comment by GarthDB** [comment]
I'm Garth Braithwaite. I'm a designer and FED living in Idaho. I work at Adobe on the PhoneGap team previous to joining the PhoneGap team I worked on other Adobe Open Source products, including Flex, Brackets, and Topcoat..

A bit ago I spoke at BlendConf on Open Source Design, and shortly after started DesignOpen.org. The primary goal of the project is to improve the standard of design in open source projects but a close secondary goal is to help educate designers of the benefits of open source.

Now we have a few more core contributors working on it including @una and @terracomma. We also have our second group of students from the Facebook Open Academy that are dedicated to working on some new tools and research.

**Comment by paulproteus** [comment]
Hi @yoroy !

I'm one of the maintainers of openhatch.org and perhaps it makes sense to collaborate there rather than make a new project. I am OK if we make a new project here, but thought I'd make sure to bring up that idea!

**Comment by paulproteus** [comment]
Oh, but also -- I presume this issue is merely introductions, not planning, so please take this all as a self-introduction rather than me attempting to apply stop energy or anything like that! Apologies if it reads like stop energy; what I mean to say is, I'm excited that we're getting some momentum post-FOSDEM and that you're doing something to bring the community together!

**Comment by jancborchardt** [comment]
I’m [Jan](http://jancborchardt.net), interaction designer based in Germany mainly working on [ownCloud](https://owncloud.org). Back in 2011 I wrote a thesis on [Usability in Free Software](http://jancborchardt.net/usability-in-free-software). I worked as designer in several open source projects and gave a bunch of talks about it.

I connected with fellow open source designers from GNOME, Mailpile, Mozilla, Drupal, Diaspora, Ubuntu etc. for some time now. I also co-organized the Open Source Design devroom at FOSDEM to help grow this movement. Let’s go!

**Comment by una** [comment]
Hello all! I'm Una (pronounced you-na). I'm a [designer](http://unakravets.com) and  [developer](http://una.github.io) living in Austin, Texas where I'm working on the [Watson](https://github.com/IBM-Watson/patterns) team at IBM (where I've been a big advocate of open source and where we JUST got a little approval for it!). Like @GarthDB said, I've joined him and @terracomma on [Design Open](http://designopen.org/) and I am pretty involved in the Sass community. I started two Sass [meetups](http://atxsass.com). I contribute to a few various (mostly Sass-related) open source projects.

I'm *really* happy and excited to work with you all to promote open source design. I've met a lot of people at conferences and other events who are also super supportive of this initiative!

**Comment by bnvk** [comment]
@yoroy @una @jancborchardt @paulproteus @GarthDB ahoy everyone :) I just committed a slight change & idea to how we do this (see this repo), using Markdown files and directory. It will be much more flexible and awesome in the long run for building a site and data portability and such. Github comments kind of exist on their own little island and you need to interact with here, where as markdown files can be updated over time and cloned and generate Jekyll sites and... the sky's the limit :)

**Comment by evalica** [comment]
Hi! I'm Caty. I'm the interaction designer for the open source project [XWiki.org](http://www.xwiki.org), which is a generic platform for developing collaborative applications. I'm based in Iasi, Romania. 

Where I live the open source design activity is mostly non-existent, so I'm glad I can participate in this initiative and make sure open source projects will be much easier to use / nicer to look at / interact with.

**Comment by hbons** [comment]
Hello, I'm [Hylke](https://www.twitter.com/hbons). Right now I'm working as a freelance designer. Previously worked on open source projects at Intel and Red Hat and still somewhat contributing to [GNOME](http://www.gnome.org). I started the [SparkleShare](http://www.sparkleshare.org) project to make it easier for designers and developers in open source to work together.

**Comment by hennevogel** [comment]
Hey I'm [Henne](http://www.hennevogel.de). I'm a full-stack web developer for [SUSE](http://www.suse.com). I get paid to hack a couple of Free and Open Source projects like the [Open Build Service](http://openbuildservice.org/), [Open Source Event Manager](http://osem.io) or [Hackweek](https://hackweek.suse.com/).  Usually I'm the only person in those projects who has at least some (self-taught) design background which makes me, more of less, their designer too I guess. :hushed: that sounds strange if you say it out loud...

I've always dreamed about having some place where I could collaborate with others on the design of open source software because I think this is one of the two big issues that is holding back wide spread adoption of it. How about we change that right here, right now? :smile_cat:

**Comment by simonv3** [comment]
Taking the same initiative as @bnvk and pushed something into the people/ directory. I think that's a much more manageable format to save than these postings. 

If anyone here wants me to make one for them because they don't have time (or any other reason) I'd be happy to, just tell me what to post according to the profile template @bnvk created.

**Comment by belenbarrospena** [comment]
Hi all. I am Belén. I am an interaction designer and design researcher, although for me both things are really the same thing. I am based in London, and I currently work for the Yocto Project. 

I started my career designing commercial software. Then, completely by chance, I landed a job working for an open source project. That was a complete eye-opener. 

I co-organised the Open Source Design devroom at FOSDEM, and will be speaking about what happened there at UXSpain in June. I believe the design work that's happening in FOSS must be made visible to the mainstream design community.

**Comment by mcginty** [comment]
Hi all! I'm Jake, and I'm with [Open Whisper Systems](https://whispersystems.org), mostly working on TextSecure, a secure messenger for Android. While I'm not a designer by any professional definition, I love it and studied Human-Computer Interaction.

Since joining the open source world in a serious way about a year ago, I've had a lot of fun talking to everybody else that's been in the community for longer about the obvious design gap. Great to see more efforts underway to help remedy that, and excited to be part of it :). Looking forward to meeting everybody at some point or another!

**Comment by sohlis** [comment]
Hello! [Stefan](http://stefansohlstrom.com/stefolio/#/) is my name. I currently work at [Plaid](http://plaid.com/) where I've been introduced to the concept of open source and have been looking for a design equivalent for a while! Based in SF.

**Comment by bnvk** [comment]
Closing this, as it should be handled in the [opensourcedesign/organization](https://github.com/opensourcedesign/organization) repo from here on out! Thanks everybody :)
