### ISSUE TITLE
Remove SCSS code from Jobs repo

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/jobs#87]
I'm trying to build and use the website locally to verify pull-requests, and it is failing due to a SCSS variable 

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting '/jobs/css/main.scss':
                    Undefined variable: "$grayscale-dark". on line 29
```

Methinks we have no need (and should not) have styling deps in each sub repo like this, as styles should be developed for the site globally in the [opensourcedesign/opensourcedesign.github.io](https://github.com/opensourcedesign/opensourcedesign.github.io) repo

**Comment by simonv3** [comment]
Agreed, I thought this had already been removed. maybe it was another sub repo.

Let me know if you figure out a dev setup that properly does all of those dependencies.

**Comment by bnvk** [comment]
@simonv3 I just nuked those files. Should I not have done that? Not quite sure I get what you mean about dev setup with dependencies...

**Comment by simonv3** [comment]
I think there's another sub-repo (events maybe?) where I removed those files already - so I was surprised they were causing you grief in this repo (I was just confused). I think you were right to do that! Though I do think there might be a repo where there are some customized styles for that specific view. 

re: dev setup dependencies: I was hoping someone would figure out a build script or something that would get the entire site to run locally. (every sub-repo). Why? It's a bit of a pain for me to edit the jobs page when I'm working offline because all the styles are missing.

**Comment by bnvk** [comment]
@simonv3 ah cool. I understand. Welp, I think I've got all of these taken care of. On your later point, I just pushed getting submodules working on some of the repos, but the Jobs one is wonky for some reason. Will investigate and finish soon!

**Comment by simonv3** [comment]
Thanks for all this work @bnvk! Can you provide a run through of how submodules work and how to get them working as well?
